/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ec.edu.ups.vista;

import ec.edu.ups.controlador.ControladorHipoteca;
import ec.edu.ups.controlador.ControladorPersona;
import ec.edu.ups.controlador.ControladorVivienda;
import javax.swing.JInternalFrame;

/**
 *
 * @author braya
 */
public class VntPrincipal extends javax.swing.JFrame {
    private ControladorPersona ctrlPersona;
    private ControladorVivienda ctrlVivienda;
    private ControladorHipoteca ctrlHipoteca;
    private VntRegistrar vntRegistrar;
    private VntVivienda vntVivienda;
    private VntHipoteca vntHipoteca;
    /**
     * Creates new form VntPrincipal
     */
    public VntPrincipal() {
        initComponents();
        //coontroladores
        ctrlPersona = new ControladorPersona();
        ctrlVivienda = new ControladorVivienda();
        ctrlHipoteca = new ControladorHipoteca();
        //ventanas
        vntRegistrar = new VntRegistrar(ctrlPersona);
        vntVivienda = new VntVivienda(ctrlVivienda, ctrlPersona);
        vntHipoteca = new VntHipoteca(ctrlPersona, ctrlVivienda, ctrlHipoteca);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        registarMenuItem = new javax.swing.JMenuItem();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        registrarViviendaMenuItem = new javax.swing.JMenuItem();
        copyMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(500, 250));
        setPreferredSize(new java.awt.Dimension(900, 700));

        fileMenu.setMnemonic('f');
        fileMenu.setText("Menu");

        registarMenuItem.setMnemonic('o');
        registarMenuItem.setText("Registrar");
        registarMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registarMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(registarMenuItem);

        exitMenuItem.setMnemonic('x');
        exitMenuItem.setText("Salir");
        exitMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic('e');
        editMenu.setText("Gestionar");

        registrarViviendaMenuItem.setMnemonic('t');
        registrarViviendaMenuItem.setText("Registrar Vivienda");
        registrarViviendaMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registrarViviendaMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(registrarViviendaMenuItem);

        copyMenuItem.setMnemonic('y');
        copyMenuItem.setText("Prestamo");
        copyMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(copyMenuItem);

        menuBar.add(editMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 650, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 576, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitMenuItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_exitMenuItemActionPerformed

    private void registarMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registarMenuItemActionPerformed
        // TODO add your handling code here:
        abrir(vntRegistrar);
    }//GEN-LAST:event_registarMenuItemActionPerformed

    private void registrarViviendaMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registrarViviendaMenuItemActionPerformed
        // TODO add your handling code here:
        abrir(vntVivienda);
    }//GEN-LAST:event_registrarViviendaMenuItemActionPerformed

    private void copyMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyMenuItemActionPerformed
        // TODO add your handling code here:
        abrir(vntHipoteca);
    }//GEN-LAST:event_copyMenuItemActionPerformed
    
    public void abrir(JInternalFrame frame){
        this.add(frame);
        frame.setVisible(true);
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VntPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VntPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VntPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VntPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VntPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem copyMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem registarMenuItem;
    private javax.swing.JMenuItem registrarViviendaMenuItem;
    // End of variables declaration//GEN-END:variables

}
